<nav class="navbar">
  <div class="navbar-top">
    <a href="./index.php" class="logo-container">
      <img src="../project2/images/logo.jpg" id="logo" alt="nexora logo">
      <span class="company-name">Nexora</span>
    </a>
  </div>

  <ul class="navbar-links">
    <li><a href="./index.php" class="directory">Home</a></li>
    <li><a href="./jobs.php" class="directory">Job Opportunities</a></li>
    <li><a href="./about.php" class="directory">About</a></li>
    <li><a href="./apply.php" class="directory">Apply</a></li>
    <li><a href="./enhancements.php" class="directory">Enhancements</a></li>
    <li><a href="./login.php" class="directory">Login</a></li>
  </ul>
</nav>